In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences

sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your video are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your video are good']

In [4]:
## define the vocabulary size
voc_size = 10000

In [5]:
## one hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3703, 9450, 5976, 8802],
 [3703, 9450, 5976, 2952],
 [3703, 5435, 5976, 2809],
 [2920, 8550, 5864, 2540, 6154],
 [2920, 8550, 5864, 2540, 5427],
 [3459, 3703, 2733, 5976, 64],
 [7330, 3157, 5634, 2540]]

In [7]:
## word embbeding representetion

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 3703 9450 5976 8802]
 [   0    0    0    0 3703 9450 5976 2952]
 [   0    0    0    0 3703 5435 5976 2809]
 [   0    0    0 2920 8550 5864 2540 6154]
 [   0    0    0 2920 8550 5864 2540 5427]
 [   0    0    0 3459 3703 2733 5976   64]
 [   0    0    0    0 7330 3157 5634 2540]]


In [10]:
## feature representation
dim = 10


In [17]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_len,)))
model.compile(optimizer='adam',loss='mse')

d:\gen-ai\python basic\python_basic\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [18]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step


array([[[ 0.04377786, -0.00115523,  0.04186858, -0.04550324,
          0.02271143,  0.040554  ,  0.04936789, -0.00329766,
          0.04783839, -0.02468538],
        [ 0.04377786, -0.00115523,  0.04186858, -0.04550324,
          0.02271143,  0.040554  ,  0.04936789, -0.00329766,
          0.04783839, -0.02468538],
        [ 0.04377786, -0.00115523,  0.04186858, -0.04550324,
          0.02271143,  0.040554  ,  0.04936789, -0.00329766,
          0.04783839, -0.02468538],
        [ 0.04377786, -0.00115523,  0.04186858, -0.04550324,
          0.02271143,  0.040554  ,  0.04936789, -0.00329766,
          0.04783839, -0.02468538],
        [-0.00554192,  0.01171758,  0.0010704 , -0.04581686,
          0.02337286,  0.00160351, -0.03604358,  0.03819752,
          0.00693319,  0.02243047],
        [ 0.01861687, -0.04071094, -0.04274304, -0.01892561,
         -0.03813845, -0.02722983, -0.04969553, -0.01334268,
         -0.01210022, -0.04090964],
        [ 0.01676795,  0.04652381, -0.01632308,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 3703, 9450, 5976, 8802], dtype=int32)

In [25]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


array([[ 0.04377786, -0.00115523,  0.04186858, -0.04550324,  0.02271143,
         0.040554  ,  0.04936789, -0.00329766,  0.04783839, -0.02468538],
       [ 0.04377786, -0.00115523,  0.04186858, -0.04550324,  0.02271143,
         0.040554  ,  0.04936789, -0.00329766,  0.04783839, -0.02468538],
       [ 0.04377786, -0.00115523,  0.04186858, -0.04550324,  0.02271143,
         0.040554  ,  0.04936789, -0.00329766,  0.04783839, -0.02468538],
       [ 0.04377786, -0.00115523,  0.04186858, -0.04550324,  0.02271143,
         0.040554  ,  0.04936789, -0.00329766,  0.04783839, -0.02468538],
       [-0.00554192,  0.01171758,  0.0010704 , -0.04581686,  0.02337286,
         0.00160351, -0.03604358,  0.03819752,  0.00693319,  0.02243047],
       [ 0.01861687, -0.04071094, -0.04274304, -0.01892561, -0.03813845,
        -0.02722983, -0.04969553, -0.01334268, -0.01210022, -0.04090964],
       [ 0.01676795,  0.04652381, -0.01632308,  0.01714046, -0.01121478,
         0.03090615, -0.0283832 ,  0.01663252